
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("usuarios/new", "Create usuarios")) ?>
</div>

<?php echo $this->tag->form(array("usuarios/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search usuarios</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="usuario_id">Usuario</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_rol">Usuario Of Rol</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_rol", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_nombre">Usuario Of Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_login">Usuario Of Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_password">Usuario Of Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_password", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
