
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("proveedores_direcciones/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("proveedores_direcciones", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit proveedores_direcciones</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="proveedor_id">Proveedor</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="direccion_id">Direccion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("direccion_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
