
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("proveedores_direcciones/new", "Create proveedores_direcciones")) ?>
</div>

<?php echo $this->tag->form(array("proveedores_direcciones/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search proveedores_direcciones</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="proveedor_direccion_id">Proveedor Of Direccion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_direccion_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="proveedor_id">Proveedor</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="direccion_id">Direccion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("direccion_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
