<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("proveedores_direcciones/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("proveedores_direcciones/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Proveedor Of Direccion</th>
            <th>Proveedor</th>
            <th>Direccion</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $proveedores_direccione) { ?>
        <tr>
            <td><?php echo $proveedores_direccione->proveedor_direccion_id ?></td>
            <td><?php echo $proveedores_direccione->proveedor_id ?></td>
            <td><?php echo $proveedores_direccione->direccion_id ?></td>
            <td><?php echo $this->tag->linkTo(array("proveedores_direcciones/edit/" . $proveedores_direccione->proveedor_direccion_id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("proveedores_direcciones/delete/" . $proveedores_direccione->proveedor_direccion_id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("proveedores_direcciones/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("proveedores_direcciones/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("proveedores_direcciones/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("proveedores_direcciones/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
