
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("roles_permisos/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("roles_permisos", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit roles_permisos</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="rol_id">Rol</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rol_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_id">Permiso</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
