
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("roles_permisos/new", "Create roles_permisos")) ?>
</div>

<?php echo $this->tag->form(array("roles_permisos/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search roles_permisos</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="rol_permiso_id">Rol Of Permiso</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rol_permiso_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="rol_id">Rol</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rol_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_id">Permiso</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
