<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("roles_permisos/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("roles_permisos/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Rol Of Permiso</th>
            <th>Rol</th>
            <th>Permiso</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $roles_permiso) { ?>
        <tr>
            <td><?php echo $roles_permiso->rol_permiso_id ?></td>
            <td><?php echo $roles_permiso->rol_id ?></td>
            <td><?php echo $roles_permiso->permiso_id ?></td>
            <td><?php echo $this->tag->linkTo(array("roles_permisos/edit/" . $roles_permiso->rol_permiso_id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("roles_permisos/delete/" . $roles_permiso->rol_permiso_id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("roles_permisos/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("roles_permisos/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("roles_permisos/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("roles_permisos/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
