
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("usuarios/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("usuarios", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit usuarios</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="usuario_rol">Rol del Usuario</label>
        </td>
        <td align="left">
            <?php echo $this->tag->selectField (array("usuario_rol", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_nombre">Nombre de Usuario</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_login">Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_password">Contraseña Actual</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_password_new">Nueva Contraseña</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="usuario_password_new_confirm">Confirmar Nueva Contraseña</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("usuario_password", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
