<?php echo $this->tag->form("session/start") ?>
<div class="container" style="margin-left: 40%; margin-right: 40%; margin-top: 5%">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Por favor, ingrese al sistema</h3>
                </div>
                <div class="panel-body">
                    <fieldset>
                        <div class="form-group">
                            <?php echo $this->tag->textField(array("email", "size" => 30, "class" => "form-control")) ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->tag->passwordField(array("password", "size" => 30, "class" => "form-control")) ?>
                        </div>
                        <div class="checkbox">
                            <label>
                                <?php
                                echo $this->tag->checkField(array("recordar", "value" => 1)) . 'Recordarme';
                                ?>
                            </label>
                        </div>
                        <?php echo $this->tag->submitButton(array("Login", "class" => "btn btn-lg btn-success btn-block")) ?>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>
</form>