
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("permisos/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("permisos", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit permisos</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="permiso_nombre">Permiso Of Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_descripcion">Permiso Of Descripcion</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("permiso_descripcion", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_controller">Permiso Of Controller</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_controller", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_accion">Permiso Of Accion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_accion", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
