
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("permisos/new", "Create permisos")) ?>
</div>

<?php echo $this->tag->form(array("permisos/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search permisos</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="permiso_id">Permiso</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_nombre">Permiso Of Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_descripcion">Permiso Of Descripcion</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("permiso_descripcion", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_controller">Permiso Of Controller</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_controller", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="permiso_accion">Permiso Of Accion</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("permiso_accion", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
