
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("roles/new", "Create roles")) ?>
</div>

<?php echo $this->tag->form(array("roles/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search roles</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="rol_id">Rol</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rol_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="rol_nombre">Rol Of Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("rol_nombre", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
