<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("roles/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("roles/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Rol</th>
            <th>Rol Of Nombre</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $role) { ?>
        <tr>
            <td><?php echo $role->rol_id ?></td>
            <td><?php echo $role->rol_nombre ?></td>
            <td><?php echo $this->tag->linkTo(array("roles/edit/" . $role->rol_id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("roles/delete/" . $role->rol_id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("roles/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("roles/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("roles/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("roles/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
