
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("proveedores/new", "Create proveedores")) ?>
</div>

<?php echo $this->tag->form(array("proveedores/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search proveedores</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="proveedor_id">Proveedor</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="proveedor_nombre">Proveedor Of Nombre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_nombre", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="proveedor_email">Proveedor Of Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="proveedor_telefono">Proveedor Of Telefono</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_telefono", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="proveedor_celular">Proveedor Of Celular</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("proveedor_celular", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
